[package]
name = "ranger"
version = "0.1.0"
authors = ["Hidde Bultsma <hidde.bultsma@bloomon.nl>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
regex = "1"
